### ISSUE TITLE
EB 2.7.0 on Santis: ASE with dummy toolchain fails sanity check

### ISSUE THREAD

**Issue by lucamar** [eth-cscs/tools#7]
I've tried to build ASE without the reference to a toolchain, as we have successfully built the dependencies with dummy toolchain (Python, etc...). While ASE-3.9.1-CrayGNU-2015.11-Python-2.7.11.eb was working with the development version, the new ASE-3.9.1-Python-2.7.11.eb fails.

$ eb ASE-3.9.1-Python-2.7.11.eb -r
== temporary log file in case of crash /tmp/eb-dqvDiH/easybuild-O0EOGw.log
== resolving dependencies ...
== processing EasyBuild easyconfig /users/lucamar/easybuildinstall/configs/ASE-3.9.1-Python-2.7.11.eb
== building and installing ASE/3.9.1-Python-2.7.11...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== postprocessing...
== sanity checking...
== FAILED: Installation ended unsuccessfully (build directory: /dev/shm/lucamar/ASE/3.9.1/dummy-dummy-Python-2.7.11): build failed (first 300 chars): Sanity check failed: no (non-empty) directory of ('lib/python2.7/site-packages/ase',) in /apps/santis/UES/5.2.UP04/sandbox-lm/easybuild/software/ASE/3.9.1-Python-2.7.11
== Results of the build can be found in the log file /tmp/eb-dqvDiH/easybuild-ASE-3.9.1-20160321.210118.gFtTt.log
ERROR: Build of /users/lucamar/easybuildinstall/configs/ASE-3.9.1-Python-2.7.11.eb failed (err: "build failed (first 300 chars): Sanity check failed: no (non-empty) directory of ('lib/python2.7/site-packages/ase',) in /apps/santis/UES/5.2.UP04/sandbox-lm/easybuild/software/ASE/3.9.1-Python-2.7.11")

**Comment by gppezzi** [comment]
Python-2.7.11.eb (dummy toolchain) was created to replace system python and it doesn't contain the scientific packages. The idea was to make it available on somewhere like /apps/common and to be used where system python has broken setuptools/pip. This is not supposed to be used as replacement for our python from CrayGNU. 

And why are you using the dummy toolchain also for ASE?

**Comment by lucamar** [comment]
ASE does not depend on MPI, therefore I thought it could be implemented for any system. It is needed by GPAW, that makes use of MPI and will need to be linked to a toolchain instead.

**Comment by gppezzi** [comment]
well the toolchain defines much more than just MPI and if the sanity checking is failing is probably because something is really missing. 

Please try it with CrayGNU as before, since we shouldn't be using dummy toolchain here: it is error prone as the build depends on the loaded modules and variables defined on your current shell. While using a proper toolchain will load the required modules and export the key variables for properly compiling and linking.

**Comment by gppezzi** [comment]
I think that dummy toolchain should be really limited to special cases and you should do module purge before building, to make sure you' re compiling only against system software.

**Comment by lucamar** [comment]
I've followed your advice and I could build without failures the following packages:
ASE-3.10.0-CrayGNU-2015.11-Python-2.7.11.eb
ASE-3.10.0-CrayGNU-2016.03-Python-2.7.11.eb

So you're right, something was missing from the PrgEnv. Sometimes however it works (e.g.: Boost).
Furthermore, I would try using the dummy toolchain version of these Python dependencies below:
bzip2-1.0.6
zlib-1.2.8
ncurses-6.0
libreadline-6.3
libpng-1.6.16
freetype-2.5.5

**Comment by boegel** [comment]
There's a thin balance between using the `dummy` toolchain and a 'proper' toolchain, indeed.

A couple of things to take into account:

* EB does very little in terms of setting up the build environment for a `dummy` toolchain, which does not seem a good idea on Cray systems since you'll be combining these builds with who-knows-what (likely with a different `PrgEnv` module than the one that was loaded)
* you're fully relying on whatever the systems provides at the time, and the modules that are loaded at that time (or not); so, your `dummy` built modules may start failing after system updates, or after module defaults are updated
