### ISSUE TITLE
GROMACS CUDA 7.0 easyconfig fails to install on Cray XC30

### ISSUE THREAD

**Issue by lucamar** [eth-cscs/tools#8]
I raise this issue that might be addressed during the Easybuild hackathon.

GROMACS-5.1.2-CrayGNU-2016.03-cuda-7.0.eb can be found in /apps/common/UES/easybuild/cscs_easyconfigs/g/GROMACS. It requires the easyblocks boostcray.py and gromacscray.py that can be found in $EASYBUILD_INCLUDE_EASYBLOCKS.
The easyconfig builds a working MPI executable gmx_mpi, but it fails make check with the error:
No rule to make target `-L/opt/cray/libsci/13.2.0/GNU/4.9/x86_64/lib', needed by `lib/libgromacs_mpi.so.1.2.0'
The issue is likely related to dynamic libraries, since the static library libgromacs_mpi.a is built instead successfully by the easyconfig GROMACS-5.1.2-CrayGNU-2016.03.eb (no dynamic option selected for the toolchain and GMX_PREFER_STATIC_LIBS flag is used during the configure step).

Previously there's a warning on cray-libsci in the log:
-- Looking for dgemm_ - not found
CMake Warning at cmake/gmxManageLinearAlgebraLibraries.cmake:78 (message):
 GMX_BLAS_USER library
 /dev/shm/lucamar/GROMACS/5.1.2/CrayGNU-2016.03-cuda-7.0/gromacs-5.1.2/-L/opt/cray/libsci/16.03.1/GNU/4.9/x86_64/lib
 was specified, but it may not provide BLAS.  We are proceeding by assuming you know what you are doing and that linking F77-style to this library will work.

Skipping the test step does not help either, as the install step would fail with the same error.

**Comment by gppezzi** [comment]
Do you have a working version of this recipe without easybuild?

**Comment by lucamar** [comment]
Sure, this is the build script that I have used recently with CMake on Piz Daint for Gromacs-5.1.2:
/apps/daint/sandbox/lucamar/src/build/gromacs-xc30_gnu-single_mpi_gpu.cmake
The only difference here is that I have used the defaul CUDA 6.5 in the manual build for production.

**Comment by lucamar** [comment]
The script above could build successfully the shared libraries of Gromacs-5.1.2 using the latest PrgEnv-gnu on Santis with the latest cudatoolkit (I haven't loaded Boost, but I got the failure also without Boost when using the Easybuild easyconfig):
$ ls -ltrh /apps/santis/sandbox/lucamar/bin/gmx512/lib64/
lrwxrwxrwx 1 lucamar csstaff   19 23 mar 19.02 libgromacs_mpi.so -> libgromacs_mpi.so.1*
lrwxrwxrwx 1 lucamar csstaff   23 23 mar 19.02 libgromacs_mpi.so.1 -> libgromacs_mpi.so.1.2.0*
-rwxr-xr-x 1 lucamar csstaff  32M 23 mar 19.02 libgromacs_mpi.so.1.2.0

**Comment by gppezzi** [comment]
@lucamar 

I've created a new easyconfig (GROMACS-5.1.2-CrayGNU-2016.03-cuda-7.0.eb-gpp) with a couple of fixes:
  * Removed toolchain option openmp (not yet implemented on Cray* toolchains, so it translates to adding the flag `-True` to the wrappers)
  * Removed toolchain option dynamic (it is true by default on Cray*)

I've also updated the [gromacs easyblock](https://gist.github.com/gppezzi/bda773383d5d9e9343af66af9211325c) (on our local EB 2.8.1 installation):
 * I've added:
```
if self.toolchain.name.startswith('Cray'):
    self.cfg.update('configopts', '-DGMX_%s_USER="%s/libsci_gnu_mpi.a"' % (libname, lib_dir))
else:
     self.cfg.update('configopts', '-DGMX_%s_USER="-L%s %s"' % (libname, lib_dir, libs))
```
  * On the Gromacs documentation they point directly to the .a that contains BLAS and LAPACK (this fixes the dgemm problem you were seeing). BTW, this `libs` variable is empty with CrayGNU.

* Fixed install step and the sanity check to look for .so instead of .a

The original easyblock hardcodes the check for static libraries, my workaround was to test if we're using the cray toolchain and then check for .so, however we need to find a proper solution (@boegel, how about testing for the toolchain option dynamic?)

**Comment by gppezzi** [comment]
@lucamar the build is here (not yet tested): 
```
module use /apps/daint/UES/5.2.UP04/sandbox-craystable/easybuild/modules/all
module load GROMACS/5.1.2-CrayGNU-2016.03-cuda-7.0
```

**Comment by boegel** [comment]
@gppezzi you can us `self.toolchain.options['dynamic']` to check the `dynamic` toolchain option.

If the modifications to the GROMACS easyblock work out, please open a pull request for them.

Also, the `openmp` problem should be easy to fix?

**Comment by gppezzi** [comment]
already fixed and tested, see https://github.com/eth-cscs/tools/issues/16
