### ISSUE TITLE
RegressionEB

### ISSUE THREAD

**Issue by jgphpc** [eth-cscs/tools#9]
Hi,

On https://jenkins.cscs.ch/view/RegressionEB/, 
while (brisi/dora) build configuration are identical (same for santis/daint), there are some differences between (brisi/dora) and (santis/daint):

* Missing in santis/daint build configuration:
```
< == building and installing Boost/1.59.0-CrayGNU-5.2.82-Python-2.7.10...
< == building and installing UDUNITS/.2.1.24-CrayGNU-5.2.82...
< == building and installing ncview/2.1.6-CrayGNU-5.2.82...
```

* Missing in brisi/dora build configuration:
```
> == building and installing h5py/2.5.0-CrayGNU-5.2.82-Python-3.4.3-parallel...
> == building and installing h5py/2.5.0-CrayGNU-5.2.82-Python-3.4.3-serial...
```

Should they be added to the jenkins build configurations ?

jg.

**Comment by gppezzi** [comment]
The lists should be the identical for Daint/Dora/Brisi/Santis, except for the packages depending on cuda.

I've updated jenkins to retrieve the list from a file (that is also available on github) and from now on we can keep the lists of packages updated here:
 * https://github.com/eth-cscs/tools/tree/master/easybuild/production

I've updated all packages to the latest toolchain version (2015.11) that will be used for the next maintenances in May. Can you please check if I'm missing something?  

UDUNITS was installed as dependency, but I don't remember for which package. If nobody is asking for it, there's no need to add it explicitly.

**Comment by jgphpc** [comment]
nothing depends on udunits.

**Comment by gppezzi** [comment]
In this case you can add it to apps/common [here](https://github.com/eth-cscs/tools/blob/master/easybuild/production/common-SLES11-2016.04)

**Comment by jgphpc** [comment]
##### https://github.com/eth-cscs/tools/blob/master/easybuild/production/MCH-RH6.7-15.11
I would **_suggest_** for the future to also build the following packages with the dummy toolchain in ```/apps/common/UES/RHAT6/easybuild``` (instead of gmvolf) ? 
* Autoconf, Automake, Autotools, CMake, Doxygen, M4, UDUNITS, Tcl, cURL, expat, flex, freetype, libreadline, libtool, ncurses.

Not so important...

**Comment by gppezzi** [comment]
1. We're not planning to change production MCH builds, we can discuss about that when we prepare the next major upgrade. 

2. Generic modules on /apps/common are currently just for testing, we need to plan carefully changes in production. Please don't touch your modules, as we're not yet planning to add that to the modulepath of kesch/escha (or any other machine) soon.

3. Using dummy for build tools (CMake, autotools) may make sense to avoid providing lots of versions of the same module. However, I really don't see a big advantage of moving dependencies outside the toolchain: the build results may vary depending on the modules loaded on the current shell. So we lose on reproducibility and that's one of the main point of using EB (+ proper toolchains). These dependencies are hidden anyway and they don't require a long build time. 

JG I see that you like dummy toolchain, but please let's avoid chaos. If you other reasons to keep moving things to dummy that I'm not aware, please share with us.

**Comment by boegel** [comment]
I think @jgphpc's main reason for resorting to the `dummy` toolchain is to avoid having the reinstall the same version of a software package multiple times with just a different toolchain, which is a valid concern.

The WIP on support for minimal toolchains may help here (cfr. http://easybuild.readthedocs.org/en/latest/Manipulating_dependencies.html#minimal-toolchains). This was implemented by @ocaisa (JSC) for exactly the reason mentioned above.

Using the `dummy` toolchain may raise issues later though, when you're trying to reinstall modules you successfully installed before, since you're very much reliant on what the OS provides.

A potential middle ground is to use a compiler-only toolchain like `GCC/4.9.3-2.25` for building 'base' tools, since that takes away the biggest concern of using the `dummy` toolchain, while maximising the potential for reusing the same module in software stacks using multiple different toolchains.

**Comment by ocaisa** [comment]
We have chosen to use `GCCcore` as the location for common utilities like the ones mentioned here. The problem with chosing `GCC` is that this causes issues when you use a module naming hierarchy. In this case, one should in general be strict about not having multiple compilers loaded at once and since `GCC` is a compiler, it shouldn't be loaded at the same time as the intel compilers. In effect, for us, `GCCcore` is a higher level replacement for `dummy`
